#!/usr/bin/env python3
"""
Script to plot histograms from CSV data files.
This script expects CSV files generated by the histogram program or generate_histogram_data.py
"""

import matplotlib.pyplot as plt
import csv
import sys
import os

def load_histogram_csv(filename):
    """Load histogram data from CSV file."""
    bins = []
    counts = []
    try:
        with open(filename, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                bins.append(int(row['bin']))
                counts.append(int(row['count']))
    except FileNotFoundError:
        print(f"Warning: {filename} not found. Skipping.", file=sys.stderr)
        return None, None
    except KeyError:
        # Try alternative format
        with open(filename, 'r') as f:
            reader = csv.reader(f)
            next(reader)  # Skip header
            for row in reader:
                if len(row) >= 2:
                    bins.append(int(row[0]))
                    counts.append(int(row[1]))
    return bins, counts

def plot_histogram(bins, counts, title, filename, array_length, threads_per_block, num_blocks):
    """Plot a single histogram."""
    fig, ax = plt.subplots(figsize=(12, 6))
    
    # Create bar chart
    ax.bar(bins, counts, width=1.0, edgecolor='black', linewidth=0.1)
    
    ax.set_xlabel('Bin Index', fontsize=12)
    ax.set_ylabel('Count', fontsize=12)
    ax.set_title(f'{title}\nArray Length: {array_length}, Threads/Block: {threads_per_block}, Blocks: {num_blocks}', 
                 fontsize=14, fontweight='bold')
    ax.grid(True, alpha=0.3)
    
    # Set reasonable x-axis limits
    if bins:
        ax.set_xlim(0, max(bins) + 1)
    
    plt.tight_layout()
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    print(f"Saved plot to {filename}")
    plt.close()

def main():
    array_lengths = [1024, 10240, 102400, 1024000]
    distribution_types = ['uniform', 'normal']
    threads_per_block = 256
    
    # Calculate number of blocks for each array length
    def calc_blocks(length):
        return (length + threads_per_block - 1) // threads_per_block
    
    for length in array_lengths:
        num_blocks = calc_blocks(length)
        for dist_name in distribution_types:
            csv_filename = f'histogram_{length}_{dist_name}.csv'
            png_filename = f'histogram_{length}_{dist_name}.png'
            
            bins, counts = load_histogram_csv(csv_filename)
            
            if bins is not None and counts is not None:
                title = f'Histogram - {dist_name.capitalize()} Distribution'
                plot_histogram(bins, counts, title, png_filename, 
                             length, threads_per_block, num_blocks)
            else:
                print(f"Skipping {csv_filename} - file not found or could not be parsed")

if __name__ == '__main__':
    # Check if matplotlib is available
    try:
        import matplotlib
        matplotlib.use('Agg')  # Use non-interactive backend
        main()
    except ImportError:
        print("Error: matplotlib is not installed. Install it with: pip install matplotlib", file=sys.stderr)
        sys.exit(1)

